pipeline {
    agent any

    environment {
        TARGET_BRANCH = 'develop-be'  // 목표 브랜치 이름 설정
        REMOTE_USER = 'ubuntu'
        REMOTE_HOST = 'j11b305.p.ssafy.io'
        REMOTE_DIR = '/home/ubuntu/newzy'  // 원격 서버에서 프로젝트가 위치한 경로
    }

    stages {
        stage('Check Branch') { // 내가 원하는 브랜치인지 필터링 진행
            when {
                expression {
                    return env.GIT_BRANCH == "origin/${TARGET_BRANCH}"
                }
            }
            steps {
                echo "Building branch: ${env.GIT_BRANCH}"
            }
        }
        stage('Cleanup Workspace') {
            steps {
                deleteDir() // 작업 공간 초기화
            }
        }
        stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                              branches: [[name: "*/${TARGET_BRANCH}"]],
                              doGenerateSubmoduleConfigurations: false,
                              extensions: [[$class: 'CleanCheckout']],
                              userRemoteConfigs: [[url: 'https://lab.ssafy.com/s11-bigdata-recom-sub1/S11P21B305.git',
                              credentialsId: 'gitlab-token']]  // credentialsId를 올바르게 설정
                    ])
                }
            }
        }
        stage('Create Directories') {
            steps {
                script {
                    // 필요한 디렉토리 생성
                    sh 'mkdir -p ${WORKSPACE}/scheduling/src/main/resources'
                }
            }
        }
        stage('Copy application.yml') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'application-scheduling-yml', variable: 'APP_YML')]) {
                        // 파일 복사
                        sh 'cp $APP_YML scheduling/src/main/resources/application.yml'

                        // 복사된 파일 내용 확인
                        sh 'cat scheduling/src/main/resources/application.yml'
                    }
                }
            }
        }
        stage('Build with Gradle') {
            steps {
                dir('scheduling') {
                    sh 'chmod +x ./gradlew'  // 실행 권한 추가
                    sh './gradlew clean build --no-daemon'
                    sh 'ls -la build/test-results/test'  // 테스트 결과 파일 경로 출력
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // JAR 파일을 이용하여 Docker 이미지 빌드
                    sh 'docker build -t backend:latest -f scheduling/Dockerfile scheduling/.'
                }
            }
        }
        stage('Deploy with deploy_backend.sh') {
            steps {
                script {
                    sh """
                        ssh -o StrictHostKeyChecking=no -i /var/jenkins_home/.ssh/jenkins_rsa ${REMOTE_USER}@${REMOTE_HOST} "
                        cd ${REMOTE_DIR} &&
                        docker-compose stop scheduling &&
                        docker-compose rm -f scheduling &&
                        docker-compose up -d scheduling &&
                        docker container prune -f &&
                        docker image prune -a -f
                        "
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
