// 게시물 데이터 예시
export const posts = [
    {
      id: 1,
      date: '2024-09-19',
      views: 123,
      likes: 10,
      title: '첫 번째 게시물 제목입니다 첫 번째 게시물 제목입니다 첫 번째 게시물 제목입니다 첫 번째 게시물 제목입니다',
      content: '여기에 게시물의 일부 내용이 표시됩니다. 이 내용을 읽고 본문을 더 확인하고 싶다면 클릭하세요.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 2,
      date: '2024-09-18',
      views: 98,
      likes: 20,
      title: '두 번째 게시물 제목입니다',
      content: '두 번째 게시물의 내용 일부입니다. 여기에 간략한 내용을 입력하세요.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 3,
      date: '2024-09-17',
      views: 150,
      likes: 30,
      title: '세 번째 게시물 제목입니다',
      content: '세 번째 게시물의 일부 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 4,
      date: '2024-09-16',
      views: 200,
      likes: 40,
      title: '네 번째 게시물 제목입니다',
      content: '네 번째 게시물의 간략한 내용.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 5,
      date: '2024-09-15',
      views: 75,
      likes: 5,
      title: '다섯 번째 게시물 제목입니다',
      content: '다섯 번째 게시물의 내용이 여기에 표시됩니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 6,
      date: '2024-09-14',
      views: 55,
      likes: 8,
      title: '여섯 번째 게시물 제목입니다',
      content: '여섯 번째 게시물의 일부 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 7,
      date: '2024-09-13',
      views: 130,
      likes: 15,
      title: '일곱 번째 게시물 제목입니다',
      content: '일곱 번째 게시물의 내용 일부입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 8,
      date: '2024-09-12',
      views: 80,
      likes: 25,
      title: '여덟 번째 게시물 제목입니다',
      content: '여덟 번째 게시물의 간략한 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 9,
      date: '2024-09-11',
      views: 160,
      likes: 18,
      title: '아홉 번째 게시물 제목입니다',
      content: '아홉 번째 게시물의 일부 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 10,
      date: '2024-09-10',
      views: 120,
      likes: 22,
      title: '열 번째 게시물 제목입니다',
      content: '열 번째 게시물의 간략한 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 11,
      date: '2024-09-09',
      views: 95,
      likes: 14,
      title: '열한 번째 게시물 제목입니다',
      content: '열한 번째 게시물의 일부 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 12,
      date: '2024-09-08',
      views: 140,
      likes: 33,
      title: '열두 번째 게시물 제목입니다',
      content: '열두 번째 게시물의 간략한 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 13,
      date: '2024-09-07',
      views: 115,
      likes: 19,
      title: '열세 번째 게시물 제목입니다',
      content: '열세 번째 게시물의 일부 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 14,
      date: '2024-09-06',
      views: 100,
      likes: 12,
      title: '열네 번째 게시물 제목입니다',
      content: '열네 번째 게시물의 간략한 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 15,
      date: '2024-09-05',
      views: 85,
      likes: 9,
      title: '열다섯 번째 게시물 제목입니다',
      content: '열다섯 번째 게시물의 일부 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 16,
      date: '2024-09-04',
      views: 70,
      likes: 7,
      title: '열여섯 번째 게시물 제목입니다',
      content: '열여섯 번째 게시물의 간략한 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 17,
      date: '2024-09-03',
      views: 60,
      likes: 4,
      title: '열일곱 번째 게시물 제목입니다',
      content: '열일곱 번째 게시물의 일부 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 18,
      date: '2024-09-02',
      views: 50,
      likes: 3,
      title: '열여덟 번째 게시물 제목입니다',
      content: '열여덟 번째 게시물의 간략한 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 19,
      date: '2024-09-01',
      views: 30,
      likes: 2,
      title: '열아홉 번째 게시물 제목입니다',
      content: '열아홉 번째 게시물의 일부 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
    {
      id: 20,
      date: '2024-08-31',
      views: 25,
      likes: 1,
      title: '스무 번째 게시물 제목입니다',
      content: '스무 번째 게시물의 간략한 내용입니다.',
      thumbnail: 'https://via.placeholder.com/100',
    },
  ];  