pipeline {
    agent any

    environment {
        TARGET_BRANCH = 'develop-data'  // 목표 브랜치 이름 설정
        REMOTE_USER = 'ubuntu'
        REMOTE_HOST = 'j11b305.p.ssafy.io'
        REMOTE_DIR = '/home/ubuntu/newzy'  // 원격 서버에서 프로젝트가 위치한 경로
    }

    stages {
        stage('Check Branch') { // 내가 원하는 브랜치인지 필터링 진행
            when {
                expression {
                    return env.GIT_BRANCH == "origin/${TARGET_BRANCH}"
                }
            }
            steps {
                echo "Building branch: ${env.GIT_BRANCH}"
            }
        }
        stage('Cleanup Workspace') {
            steps {
                deleteDir() // 작업 공간 초기화
            }
        }
        stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                              branches: [[name: "*/${TARGET_BRANCH}"]],
                              doGenerateSubmoduleConfigurations: false,
                              extensions: [[$class: 'CleanCheckout']],
                              userRemoteConfigs: [[url: 'https://lab.ssafy.com/s11-bigdata-recom-sub1/S11P21B305.git',
                              credentialsId: 'gitlab-token']]  // credentialsId를 올바르게 설정
                    ])
                }
            }
        }
        stage('Copy .env') {
            steps {
               script {
                    withCredentials([file(credentialsId: 'crawl-env', variable: 'ENV_FILE')]) {
                        // .env 파일 복사
                        sh 'cp $ENV_FILE crawl/.env'

                        // 복사된 파일 내용 확인
                        sh 'cat crawl/.env'
                    }
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Django 프로젝트를 Docker 이미지로 빌드
                    sh 'docker build -t crawl:latest -f crawl/Dockerfile crawl/.'
                }
            }
        }
        stage('Deploy with docker-compose') {
            steps {
                script {
                    // SSH 키를 사용하여 원격 서버에 연결하고 배포 스크립트 실행
                    sh """
                        ssh -o StrictHostKeyChecking=no -i /var/jenkins_home/.ssh/jenkins_rsa ${REMOTE_USER}@${REMOTE_HOST} "
                        cd ${REMOTE_DIR} &&
                        docker-compose stop crawl &&
                        docker-compose rm -f crawl &&
                        docker-compose up -d crawl &&
                        docker container prune -f &&
                        docker image prune -a -f
                        "
                    """
                }
            }
        }

        stage('Notification') {  // 알림 추가
            steps {
                echo 'jenkins notification!'
            }
            post {
                success {
                    script {
                        def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                        def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                        mattermostSend(color: 'good',
                            message: "배포 성공: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                            endpoint: 'https://meeting.ssafy.com/hooks/xnw8ojosjpbczjqcq1g1c8yg7e',
                            channel: 'Jenkins_Build_Result'
                        )
                    }
                }
                failure {
                    script {
                        def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                        def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                        mattermostSend(color: 'danger',
                            message: "배포 실패: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                            endpoint: 'https://meeting.ssafy.com/hooks/xnw8ojosjpbczjqcq1g1c8yg7e',
                            channel: 'Jenkins_Build_Result'
                        )
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                def color = currentBuild.result == 'SUCCESS' ? 'good' : 'danger'
                def message = "${currentBuild.result == 'SUCCESS' ? '배포 성공' : '배포 실패'}: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)"
                
                mattermostSend(color: color,
                    message: message,
                    endpoint: 'https://meeting.ssafy.com/hooks/xnw8ojosjpbczjqcq1g1c8yg7e',
                    channel: 'Jenkins_Build_Result'
                )
            }
        }
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
